#################### Maintained by Hatch ####################
# This file is auto-generated by hatch. If you'd like to customize this file
# please add your changes near the bottom marked for 'USER OVERRIDES'.
# EVERYTHING ELSE WILL BE OVERWRITTEN by hatch.
#############################################################
from io import open

from setuptools import find_packages, setup

with open("{{cookiecutter.project_slug}}/__init__.py", "r") as f:
    for line in f:
        if line.startswith("__version__"):
            version = line.strip().split("=")[1].strip(" '\"")
            break
    else:
        version = "0.0.1"

with open("README.rst", "r", encoding="utf-8") as f:
    readme = f.read()

REQUIRES = []

kwargs = {
    "name": "{{cookiecutter.project_slug}}",
    "version": version,
    "description": "",
    "long_description": readme,
    "author": "{{cookiecutter.project_author}}",
    "author_email": "{{cookiecutter.project_author_email}}",
    "maintainer": "{{cookiecutter.project_author}}",
    "maintainer_email": "{{cookiecutter.project_author_email}}",
    "url": "{{cookiecutter.project_url}}",
    "license": "MIT",
    "classifiers": [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    "install_requires": REQUIRES,
    "tests_require": ["coverage", "pytest"],
    "packages": find_packages(exclude=("tests", "tests.*")),
}

#################### BEGIN USER OVERRIDES ####################
# Add your customizations in this section.


kwargs["install_requires"] = ["schedule", "humbletray>=0.0.21"]
kwargs["include_package_data"] = True


###################### END USER OVERRIDES ####################

setup(**kwargs)
